### PR TITLE
Revert "Speedup UnitDependencyOptionValue completion "

### PR DESCRIPTION
**Pull request by SJrX**
Reverts SJrX/systemdUnitFilePlugin#232

Hey @VladRassokhin 

I think I need to revert this MR, JetBrains has rejected the release, I believe because of this:

https://github.com/SJrX/systemdUnitFilePlugin/pull/232/files#diff-591e7f8462f95e8ff6c535d6005073af9eb7be1a9992314f13acf14b09413338R119

Although I guess I'm not sure if it's exactly that. The report I got was : 

> The [latest update of your plugin](https://plugins.jetbrains.com/plugin/11070-unit-file-support-systemd-/edit/versions/stable/475957) uses API annotated with org.jetbrains.annotations.ApiStatus.Internal. Such APIs are private and cannot be used outside the IntelliJ Platform itself.

I'm not 100% sure I will revert it, but it will be a bit before I can look at this. So I wanted to give you a heads up.

### CODE REVIEW

**Comment by VladRassokhin** [comment]
It's not allowing to publish a new version, or just complains that it uses internal API? 
If it's only a warning — ignore it for now :)
We can assume that that method will be there for at least 2024.1, so kinda safe to use it.

**Comment by VladRassokhin** [comment]
We can assume that that method will be there for at least 2024.1, so kinda safe to use it.

**Comment by VladRassokhin** [comment]
I've asked colleagues to approve that api usage in your plugin. So update is vailable now.

**Comment by SJrX** [comment]
Thanks @VladRassokhin .

Will I have problems with further updates? Also should I change the min version to 2024.1? 
One thing I want to do, hopefully over the next few weeks is actually glue together all the automation stuff I have to just automatically submit new builds with updates from the systemd project.

**Comment by VladRassokhin** [comment]
>Will I have problems with further updates?

AFAIU Plegun was added to the exclusion list and subsequent updates should succeed.

> should I change the min version to 2024.1?

No, that method is present in the current 'since-build' version.

>submit new builds with updates from the systemd project

I'd recommend publishing systemd-related resources in a separate repository/package and adding the "fetch new metadata" feature into the plugin, so users would be able to update metadata without updating the plugin. Used that approach for Terraform plugin for some time. Although it's indeed much simpler to just automatically build and upload IDE plugin to the marketplace.

**Pull request closed without merging**
